export default {
  version: null,
  deviceDto: {
    version: null,
    id: 9,
    deviceCode: '864908057966102',
    aliasName: '嘿哈。23',
    provinceName: '浙江省',
    cityName: '杭州市',
    groupCode: 'GRPcustomer2204220000100001',
    groupName: '白山组',
    onlineStatus: 'online',
    onlineStatusText: '在线',
    unbindFlag: 0,
  },
  metaDtos: [
    {
      version: null,
      metaKey: 'HighLv_IN',
      metaName: '高液位',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'LowLv_IN',
      metaName: '低液位',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Lift_ST',
      metaName: '提升运行状态',
      metaValue: '开',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Stir_ST',
      metaName: '搅拌运行状态',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Air_ST',
      metaName: '曝气运行状态',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Reflux_ST',
      metaName: '回流运行状态',
      metaValue: '开',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'SAN_ST',
      metaName: '消毒设备运行状态',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Lift_CS',
      metaName: '提升控制',
      metaValue: '开',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'Stir_CS',
      metaName: '搅拌控制',
      metaValue: '开',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'Air_CS',
      metaName: '曝气控制',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'Reflux_CS',
      metaName: '回流控制',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'Auto_CS',
      metaName: '自动控制',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'Stir_RunSET',
      metaName: '搅拌运行时间设置',
      metaValue: '15',
      dataType: 'INT',
      metaUnit: '分钟',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Stir_StopSET',
      metaName: '搅拌停止时间设置',
      metaValue: '0',
      dataType: 'INT',
      metaUnit: '分钟',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Air_RunSET',
      metaName: '曝气运行时间设置',
      metaValue: '30',
      dataType: 'INT',
      metaUnit: '分钟',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Air_StopSET',
      metaName: '曝气停止时间设置',
      metaValue: '0',
      dataType: 'INT',
      metaUnit: '分钟',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Reflux_RunSET',
      metaName: '回流运行时间设置',
      metaValue: '0',
      dataType: 'INT',
      metaUnit: '分钟',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Reflux_StopSET',
      metaName: '回流停止时间设置',
      metaValue: '0',
      dataType: 'INT',
      metaUnit: '分钟',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'DI_1',
      metaName: 'DI1',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'DI_2',
      metaName: 'DI2',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'DI_3',
      metaName: 'DI3',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'uploadPeriod',
      metaName: '上报周期',
      metaValue: '15',
      dataType: 'INT',
      metaUnit: 's',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'changeUpload',
      metaName: '变化上报',
      metaValue: null,
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'alarmUpload',
      metaName: '预警上报',
      metaValue: null,
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'rssi',
      metaName: '信号强度',
      metaValue: '23',
      dataType: 'TEXT',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'iccid',
      metaName: 'iccid',
      metaValue: '89861121247044315430',
      dataType: 'TEXT',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'loc',
      metaName: '定位',
      metaValue: 'e614_4b8a018',
      dataType: 'TEXT',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'IMEI',
      metaName: 'IMEI',
      metaValue: '864908057966102',
      dataType: 'TEXT',
      metaUnit: null,
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'uploadPeriod_dido',
      metaName: 'DIDO上报周期',
      metaValue: '300',
      dataType: 'INT',
      metaUnit: 's',
      orderDtos: null,
    },
  ],
  orderDtos: [
    {
      version: null,
      metaKey: 'Lift_CS',
      metaName: '提升控制',
      metaValue: '开',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'Stir_CS',
      metaName: '搅拌控制',
      metaValue: '开',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'Air_CS',
      metaName: '曝气控制',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'Reflux_CS',
      metaName: '回流控制',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'Auto_CS',
      metaName: '自动控制',
      metaValue: '关',
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'Stir_RunSET',
      metaName: '搅拌运行时间设置',
      metaValue: '15',
      dataType: 'INT',
      metaUnit: '分钟',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Stir_StopSET',
      metaName: '搅拌停止时间设置',
      metaValue: '0',
      dataType: 'INT',
      metaUnit: '分钟',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Air_RunSET',
      metaName: '曝气运行时间设置',
      metaValue: '30',
      dataType: 'INT',
      metaUnit: '分钟',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Air_StopSET',
      metaName: '曝气停止时间设置',
      metaValue: '0',
      dataType: 'INT',
      metaUnit: '分钟',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Reflux_RunSET',
      metaName: '回流运行时间设置',
      metaValue: '0',
      dataType: 'INT',
      metaUnit: '分钟',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'Reflux_StopSET',
      metaName: '回流停止时间设置',
      metaValue: '0',
      dataType: 'INT',
      metaUnit: '分钟',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'uploadPeriod',
      metaName: '上报周期',
      metaValue: '15',
      dataType: 'INT',
      metaUnit: 's',
      orderDtos: null,
    },
    {
      version: null,
      metaKey: 'changeUpload',
      metaName: '变化上报',
      metaValue: null,
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'alarmUpload',
      metaName: '预警上报',
      metaValue: null,
      dataType: 'BOOL',
      metaUnit: null,
      orderDtos: [
        { version: null, name: '关', value: 0, dataType: 'BOOL' },
        { version: null, name: '开', value: 1, dataType: 'BOOL' },
      ],
    },
    {
      version: null,
      metaKey: 'uploadPeriod_dido',
      metaName: 'DIDO上报周期',
      metaValue: '300',
      dataType: 'INT',
      metaUnit: 's',
      orderDtos: null,
    },
  ],
  unbindFlag: 1,
  orderFlag: 1,
};
