export const DATE_FORMAT_DATE = 'YYYY-MM-DD';
export const DATE_FORMAT_TIME = 'HH:mm:ss';
export const DATE_FORMAT_TIME_MINUTES = 'HH:mm';
export const DATE_FORMAT_DATETIME_HOURS = `${DATE_FORMAT_DATE} HH`;
export const DATE_FORMAT_DATETIME_MINUTES = `${DATE_FORMAT_DATE} HH:mm`;
export const DATE_FORMAT_FULL_TIME = `${DATE_FORMAT_DATE} ${DATE_FORMAT_TIME}`;
